version: "3.7"

services:
  dbv:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: odoo19
      POSTGRES_PASSWORD: odoo19@2024
      POSTGRES_DB: pgvector
    volumes:
      - odoo19_test_pgdata:/var/lib/postgresql/data
    networks:
      - public_network
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  odoo19:
    image: odoo:latest
    depends_on:
      - dbv
    environment:
      HOST: dbv
      USER: odoo19
      PASSWORD: odoo19@2024
    volumes:
      - odoo19_test_addons:/mnt/extra-addons
      - odoo19_test_config:/etc/odoo
      - odoo19_test_data:/var/lib/odoo
    networks:
      - public_network
    command: >
      bash -c "
      echo 'Waiting for Postgres...';
      until pg_isready -h dbv -p 5432 -U odoo19; do sleep 2; done;
      echo 'Starting Odoo...';
      exec odoo --db_host=dbv --db_port=5432 --db_user=odoo19 --db_password='odoo19@2024'"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.odoo19-test.rule=Host(`test.op-eg.com`)"
        - "traefik.http.routers.odoo19-test.entrypoints=websecure"
        - "traefik.http.routers.odoo19-test.tls=true"
        - "traefik.http.routers.odoo19-test.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.odoo19-test.loadbalancer.server.port=8069"

volumes:
  odoo19_test_pgdata:
  odoo19_test_addons:
  odoo19_test_config:
  odoo19_test_data:

networks:
  public_network:
    external: true
